### ISSUE TITLE
Task got run on wrong thread.

### ISSUE THREAD

**Issue by kchanqvq** [Shinmera/trivial-main-thread#7] opened 2022-01-06 07:06 UTC
I'm using `trivial-main-thread` and I find some code still got ran from non-main thread and got me drop into `ldb`. I did a bit of investigation and it seems that the issue is that `ensure-main-thread` changes the shared `*runner*` from `queued-runner` to a `runner`, causing all thread to run their task in their own thread? I'm not totally sure about the internals yet, so not sure.

Edit: unfortunately commenting out that line just causes deadlock...

**Comment by Shinmera** [comment] 2023-04-01 21:43
How are you determining that it's run from a non-main thread? What implementation is this? What version? Are you running something else that's blocking the main thread first?

**Comment by Shinmera** [comment] 2024-06-09 11:38
Closing since the implementation was rewritten and this issue is likely out of date. If you can reproduce this with the latest version still, please re-open the ticket.

**Closed by Shinmera** 2024-06-09 11:38 UTC
